### ISSUE TITLE
Fails to load on 2.0.205.52

### ISSUE THREAD

**Issue by LiefAmai** [TealTime/Clever-Girl#1]
=== Clever Girl [fork] 1.0.5 Errors ===
<...>\steamapps\workshop\content\333640\2921686606\InterfaceCompanions.cs(24,49): error CS1739: The best overload for 'ShowOptionList' does not have a parameter named 'defaultSelected'
<...>\steamapps\workshop\content\333640\2921686606\Feed.cs(90,49): error CS1739: The best overload for 'ShowOptionList' does not have a parameter named 'defaultSelected'
<...>\steamapps\workshop\content\333640\2921686606\ManageGear.cs(229,74): error CS1061: 'BodyPart' does not contain a definition for 'PreferedPrimary' and no accessible extension method 'PreferedPrimary' accepting a first argument of type 'BodyPart' could be found (are you missing a using directive or an assembly reference?)
<...>\steamapps\workshop\content\333640\2921686606\Feed.cs(375,50): error CS1739: The best overload for 'ShowOptionList' does not have a parameter named 'defaultSelected'
<...>\steamapps\workshop\content\333640\2921686606\Feed.cs(620,46): error CS1739: The best overload for 'ShowOptionList' does not have a parameter named 'defaultSelected'
== Warnings ==
<...>\steamapps\workshop\content\333640\2921686606\Feed.cs(416,80): warning CS0618: 'GameObjectBlueprint.GetPartParameter(string, string, string)' is obsolete: 'Use GetPartParameter<string> instead - will remove Q2 2023'

**Comment by LiefAmai** [comment]
Version 2.0.205.60 currently throws the same errors.

**Comment by TealTime** [comment]
Apologies, I have been engaged in other games, haven't looked at Qud in a while. First Github issue -- Exciting! (I really mean that). I (hopefully correctly) setup email notifications on Github so I should get notified for issues like this. I fixed this on the main branch a while ago, never got around to updating the beta branch. I'll see if i can get that updated now

**Comment by TealTime** [comment]
There appears to be a version mismatch here somehow, at least given the error log being shown. Not sure exactly what's going on. The error log above shows version 1.0.5, which should be showing either 1.0.6_hotfix (main branch) or v1.0.7-beta4 (beta branch). 

If you're cloning manually and using the beta branch, you might be using an older version? (should be https://github.com/TealTime/Clever-Girl/releases/tag/v1.0.7-beta4) Or if you're using the steam workshop version, maybe it's just not syncing correctly? I speculate that an unsubscribe/subscribe to the steam workshop might fix that if that is the case. I know there's been issues with updates propagating correctly in the past, which I admittedly need to investigate further.

FWIW, I'm loading the mod without errors on both the current Clever-Girl [fork] branches (main/beta) with the beta version of Caves of Qud right now, unless something in my setup is wrong (which is a definite possibility).

**Comment by TealTime** [comment]
Also if I don't reply to one of your followup messages in the near future, please ping me on the steam workshop. I'm still not confident that I've got these Github email notification settings correct

**Comment by LiefAmai** [comment]
> There appears to be a version mismatch here somehow, at least given the error log being shown. Not sure exactly what's going on. The error log above shows version 1.0.5, which should be showing either 1.0.6_hotfix (main branch) or v1.0.7-beta4 (beta branch).
> 
> If you're git-cloning manually and using the beta branch, you might be using an older version? (should be https://github.com/TealTime/Clever-Girl/releases/tag/v1.0.7-beta4) Or if you're using the steam workshop version, maybe it's just not syncing correctly? I speculate that an unsubscribe/subscribe to the steam workshop might fix that if that is the case. I know there's been issues with updates propagating correctly in the past, which I admittedly need to investigate further.
> 
> FWIW, I'm loading the mod without errors on both the current Clever-Girl [fork] branches (main/beta) with the beta version of Caves of Qud right now, unless something in my setup is wrong (which is a definite possibility).

Ahhh this was the issue apparently! It would be nice if Steam Workshop was actually capable of keeping things up to date! It loads fine once unsubbing/resubbing to force Steam to download the correct version. (Though even that's marked as v1.0.6_hotfix, but at least it loads and doesn't throw errors.)
